version: '3.9'
services:
  haproxy:
    build: 'haproxy'
    ports:
      - 5432:5432
      - 7000:7000
    depends_on:
      - zoo1
      - pg-master
      - pg-slave

  zoo1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zoo
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  pg-master:
    build: 'postgres'
    container_name: pg-master
    restart: always
    hostname: pg-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - 5432
      - 8008
    ports:
      - 5433:5432
    volumes:
     - '/var/lib/postgresql/data'
    command: patroni /postgres0.yml

  pg-slave:
    build: 'postgres'
    container_name: pg-slave
    restart: always
    hostname: pg-slave
    expose:
      - 5432
      - 8008
    ports:
      - 5434:5432
    volumes:
     - '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    command: patroni /postgres1.yml
